site_name: pytest-splunk-soar-connectors
site_description: A simple plugin to use with pytest
site_author: Daniel Federschmidt

theme: 
  name: material
  icon:
    logo: material/file-code
  palette:
    scheme: slate
    primary: green
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes 

repo_url: https://github.com/dfederschmidt/pytest-splunk-soar-connectors


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
- Home:
  - Overview: index.md
  - Installation: installation.md
- Guides:
  - Getting started: guides/getting_started.md
  - Using requests-mock: guides/using_requests_mock.md
  - Using VCR.py: guides/using_vcrpy.md
- Reference:
  - Limitations: limitations.md